IDVA3-1839 Feature/update start screen
companieshouse/psc-verification-web pull request #148
Opened 2024-08-07 14:51 UTC by JasSmith-ch

- updated the start screen
- updated the json file for english and welsh translation

2024-08-08 10:00 UTC, eedwards0 commented on locales/en/start.json
> +    "start_when_to_verify_description1": "You must wait until the company has reached its confirmation statement date before you can provide verification details for its PSCs or RLEs. You will not be
Minor - add full stop at end

2024-08-08 10:23 UTC, eedwards0 commented on locales/en/start.json
> +    "start_deatils_for_rle_description1": "You'll also need their full name and date of birth.",
rename "deatils" to "details"

2024-08-08 10:36 UTC, eedwards0 commented on locales/en/start.json
>      "start_before_verify_link": "verify their identity",
May be clearer to describe as "start_verify_link_text"

2024-08-08 10:38 UTC, eedwards0 commented on locales/en/start.json
>      "start_before_verify_description": "The PSC or relevant officer must",
```suggestion
    "start_before_verify_link": "The PSC or relevant officer must",
```

2024-08-08 10:41 UTC, eedwards0 commented on locales/en/start.json
May be clearer to rename to "start_after_verify_link"

2024-08-08 10:48 UTC, eedwards0 commented on locales/en/start.json
Line 14: May be clearer to rename "start_before_verify_description2" to "start_after_verify_link

2024-08-08 10:57 UTC, eedwards0 requested changes
Very minor text and some of the JSON fields may be clearer if renamed, as this page has had a lot of change. Also, there is an extra white space at the end of the "verify their identity" link before the comma.

2024-08-08 13:48 UTC, ch-code-analysis commented
CI: No security warnings found

2024-08-09 09:45 UTC, eedwards0 commented on locales/en/start.json
> +   "start_before_verify_link_text": "The PSC or relevant officer must",
Rename "start_before_verify_link_text" to "start_before_verify_link"

2024-08-09 09:51 UTC, eedwards0 commented on src/views/router_views/start/start.njk
>      <p class="govuk-body">{{ i18n.start_before_verify_description }}
Please update lines 31 to 35 as follows:

    <p class="govuk-body">{{ i18n.start_before_verify_link }}
        <a href="{{ [chsUrl, verifyIdentityLink] | join  }}" title="{{ i18n.start_verify_link_text }}" class="govuk-link" data-event-id="before-verify-link">
            {{ i18n.start_verify_link_text }}
        </a>
        {{i18n.start_after_verify_link}}</p>

2024-08-09 09:54 UTC, eedwards0 requested changes
Some tweaks needed - suggested changes in comments.
Also, can you take a look at removing the extra white space after the 'verify their identity' link under the 'Before you start' section?

2024-08-12 10:04 UTC, ch-code-analysis commented
CI: No security warnings found

2024-08-12 11:34 UTC, eedwards0 commented on src/views/router_views/start/start.njk
>      <ul class="govuk-list govuk-list--bullet">
Please add in: 
<p class="govuk-body">{{ i18n.start_before_list }}</p> 
after the verify link text, which ends on line 38, and before the bulleted list on line 39.

2024-08-12 11:35 UTC, eedwards0 requested changes
Just need to add back in lines before the bulleted list - added comment to start.njk

2024-08-12 16:16 UTC, ch-code-analysis commented
CI: No security warnings found

2024-08-13 08:17 UTC, eedwards0 approved these changes
Looking good :)

2024-08-15 14:18 UTC, merged