IDVA3-1663 Updated psc statement screen
companieshouse/psc-verification-web pull request #149
Opened 2024-08-15 16:02 UTC by JasSmith-ch

- updated screen to match the v9 prototype
- updated the tests to match it

2024-08-15 16:06 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-08-15 16:36 UTC, eedwards0 commented on locales/en/individual-statement.json
> +    "individual_statement_button": "Continue and submit"
Please update to "Confirm and submit"

2024-08-15 16:37 UTC, eedwards0 requested changes
Button text requires updating

2024-08-16 09:17 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-08-16 11:03 UTC, eedwards0 approved these changes
Looks good :)

2024-08-20 06:44 UTC, merged