created and added content to rle details
companieshouse/psc-verification-web pull request #52
Opened 2024-03-25 13:29 UTC by JasSmith-ch

- created and added content to rle details
- not sure why but i merged my pull request from last time and its still saying on this request that the changes will be new such as the rlePscList page and the bug fix

2024-03-25 13:33 UTC, ch-code-analysis commented
CI: No security warnings found

2024-03-25 13:40 UTC, ch-code-analysis commented
CI: No security warnings found

2024-03-25 18:18 UTC, AlisonGriffiths requested changes
Have a read through - https://design-system.service.gov.uk/components/date-input/

See the various macro options that are available to you that will help you complete this page.

2024-03-28 08:43 UTC, PhilipGlover commented on locales/cy/rle-details.json
> +    "rle_details_hint1": "To be translated",
present now and english done too

2024-03-28 08:58 UTC, ch-code-analysis commented
CI: No security warnings found

2024-03-28 10:41 UTC, PhilipGlover commented on src/views/router_views/rleDetails/rleDetails.njk
> +  {{ govukDateInput({
items added

2024-03-28 10:50 UTC, PhilipGlover commented on src/views/router_views/rleDetails/rleDetails.njk
> +    text: i18n.rle_details_hint2
added, though is it best to place this at the top of the template?  Wouldn't it be better above the start of the `govukDateInput` block? This is what I see in the start template.

2024-03-28 11:03 UTC, PhilipGlover commented on src/views/router_views/rleDetails/rleDetails.njk
> +  <div class="govuk-hint">{{i18n.rle_details_hint1}}</div>
removed

2024-03-28 11:03 UTC, PhilipGlover commented on src/views/router_views/rleDetails/rleDetails.njk
> +      isPageHeading: true,
changed to false

2024-03-28 11:03 UTC, PhilipGlover commented on src/views/router_views/rleDetails/rleDetails.njk
> +      classes: "govuk-fieldset__legend--l"
classes removed

2024-03-28 11:04 UTC, PhilipGlover commented on src/views/router_views/rleDetails/rleDetails.njk
> +  <label class="govuk-label">{{i18n.rle_details_dob_label}}</label>
removed label

2024-03-28 12:50 UTC, PhilipGlover commented on src/views/router_views/rleDetails/rleDetails.njk
> +    text: i18n.rle_details_hint2
moved ☑️

2024-03-28 13:19 UTC, merged