Spike/investigate transactions
companieshouse/psc-verification-web pull request #56
Opened 2024-03-27 14:40 UTC by clewis1

https://companieshouse.atlassian.net/browse/IDVA3-1128

Confirm a company and navigate to the psc type list screen.
Check the logs to confirm a transaction has been created.

`debug: Received transaction {"httpStatusCode":201,"resource":{"id":"181241-681217-115502","etag":"a7f287ad6fbf77a9570a7d1c1ae6a7351d19bef7","links":{"self":"/transactions/181241-681217-115502"},"reference":"PscVerificationReference","status":"open","kind":"transaction","createdAt":"2024-03-27T14:37:42Z","createdBy":{"language":"en","id":"Y2VkZWVlMzhlZWFjY2M4MzQ3MT","email":"demo@ch.gov.uk"},"updatedAt":"2024-03-27T14:37:42Z","description":"PSC Verification Transaction"}}`

2024-03-27 14:44 UTC, ch-code-analysis commented
CI: No security warnings found

2024-03-27 15:21 UTC, PhilipGlover commented on src/services/internal/api.service.ts
do we need this service at all?

2024-03-27 15:28 UTC, PhilipGlover commented on src/routers/confirmCompanyRouter.ts
> +    const transaction: Transaction = await postTransaction(session, companyNumber, DESCRIPTION, REFERENCE);
in the companyProfile service, the request is passed to it, and then it pulls out the session and company number.  I wonder if we should be consistent, whichever way we go.
Plus something doesn't seem quite appropriate about passing the DESCRIPTION and REFERENCE.  I don't know the best place, but would just having them in the transaction service for now be neater?

2024-03-27 15:29 UTC, PhilipGlover requested changes
I’ve successfully run this code and seen tx created in db.  
Couple of issues above.

2024-03-27 15:36 UTC, PhilipGlover commented on src/services/internal/transaction.service.ts
the internal / external split in services comes from the node starter project.  Whether we want to keep it I don't know.  But the transaction service is probably more external in the sense it's a public API, like the Company Profile.  The internal confirmCompany one is more providing functionality for this PSC Verify web.  Perhaps that should be a utility?  Perhaps we should scrap the internal / external split?

2024-03-27 15:42 UTC, clewis1 commented on src/services/internal/api.service.ts
I guess not now!

2024-03-27 16:52 UTC, ch-code-analysis commented
CI: No security warnings found

2024-03-28 07:58 UTC, PhilipGlover approved these changes
- changes addressed and have run the code again
- my comment re the external/internal services, can be considered late if needs be

2024-03-28 09:02 UTC, hepsimo approved these changes
Code looks good

2024-03-28 09:07 UTC, PhilipGlover commented on src/services/internal/transaction.service.ts
> +    }
I've added this question for discussion in our dev canvas

2024-03-28 09:07 UTC, merged