Feature/refactor filenames and imports
companieshouse/psc-verification-web pull request #62
Opened 2024-04-05 09:33 UTC by clewis1

https://companieshouse.atlassian.net/browse/IDVA3-1278

2024-04-05 10:33 UTC, PhilipGlover commented on test/routers/healthcheck.unit.ts
I don't think we need this test at all - in ECS the start page is used as a healthcheck.  And the 200 status is already tested in `start.unit`

2024-04-05 10:43 UTC, PhilipGlover commented on src/app.ts
>  import { logger } from "./lib/Logger";
this path needs to be `./lib/logger` now - lower case 'l'

2024-04-05 10:44 UTC, PhilipGlover commented on src/routers/confirmCompanyRouter.ts
>  import { logger } from "../lib/Logger";
`/logger` here too and in several other files

2024-04-05 10:54 UTC, PhilipGlover commented on src/routers/handlers/personal-code/personalCode.ts
the import in the personalCode router that uses this handler will need updating.

2024-04-05 10:56 UTC, PhilipGlover requested changes
not all imports have been amended, so service won't build and start

2024-04-05 13:43 UTC, ch-code-analysis commented
CI: No security warnings found

2024-04-05 14:37 UTC, PhilipGlover commented on src/types/jsonData.ts
> +/* eslint-disable no-use-before-define */
this does the beg question whether this should be kept if it's unused.  This has come from the web-starter project. 
Are we going to be using raw JSON in the web?

2024-04-08 10:55 UTC, PhilipGlover commented on src/types/jsonData.ts
> +/* eslint-disable no-use-before-define */
file removed

2024-04-08 10:55 UTC, PhilipGlover approved these changes
as per comments above

2024-04-08 12:17 UTC, merged