Add sunny day tests
companieshouse/psc-verification-web pull request #74
Opened 2024-04-25 10:40 UTC by clewis1

https://companieshouse.atlassian.net/browse/IDVA3-580

2024-04-25 10:44 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-04-25 15:25 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-04-25 15:51 UTC, eedwards0 approved these changes
All tests passing and working in Docker.

2024-04-26 07:37 UTC, PhilipGlover commented on src/routers/confirmCompanyRouter.ts
> +        }
should we be adding these optional values back in?  Simon took them out from here, since we wouldn't know them at this point in the journey.

2024-04-26 08:15 UTC, PhilipGlover submitted a review, later dismissed
- tests pass, and happy to approve.  But I think the additions to the PSC Verification data ought to come out first.

2024-04-26 09:42 UTC, clewis1 commented
Code updated to fit recommendations.

2024-04-26 09:57 UTC, PhilipGlover requested changes
I don't think the discussed code commit has been pushed.

2024-04-26 10:02 UTC, ch-code-analysis commented
CI: No security warnings found

2024-04-26 10:03 UTC, merged