IDVA3-1368 Rle verified screen
companieshouse/psc-verification-web pull request #76
Opened 2024-04-25 15:07 UTC by JasSmith-ch

- Added static content for the RLE Verified screen

2024-04-25 15:11 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-04-25 16:11 UTC, eedwards0 commented on locales/en/rle-verified.json
> +    "rle_verified_title": "RLE confirmed",
Please change to 'PSC confirmed'

2024-04-25 16:18 UTC, eedwards0 commented on locales/en/rle-verified.json
> +    "rle_verified_title": "RLE confirmed",
In the prototype v5, the title is 'PSC confirmed'. I guess we better match this one :).

2024-04-29 08:17 UTC, ch-code-analysis commented
CI: No security warnings found

2024-04-29 08:39 UTC, eedwards0 commented on locales/en/rle-verified.json
Page title is 'PSC confirmed' in prototype v5.

2024-04-29 13:50 UTC, ch-code-analysis commented
CI: No security warnings found

2024-04-30 08:31 UTC, eedwards0 requested changes
Please see individual comments

2024-04-30 08:44 UTC, ch-code-analysis commented
CI: No security warnings found

2024-04-30 09:30 UTC, eedwards0 approved these changes
All now working as expected in Docker

2024-04-30 09:51 UTC, merged