Add selectedType function and unit tests
companieshouse/psc-verification-web pull request #81
Opened 2024-05-01 08:53 UTC by clewis1

https://companieshouse.atlassian.net/browse/IDVA3-1022

2024-05-01 08:57 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-01 10:21 UTC, hepsimo requested changes
Changes look good, just need a TODO comment for a reminder

2024-05-01 10:21 UTC, hepsimo commented on src/routers/pscTypeRouter.ts
> +    default: return PrefixedUrls.INDIVIDUAL_PSC_LIST;
The default case (neither option selected) will get error handling later, so best add a TODO comment as reminder.

2024-05-01 10:35 UTC, hepsimo requested changes
Changes look good, just need a TODO comment added

2024-05-01 13:34 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-02 07:59 UTC, hepsimo approved these changes
Changes look good

2024-05-02 08:00 UTC, merged