Verification statement screen
companieshouse/psc-verification-web pull request #88
Opened 2024-05-10 12:42 UTC by PhilipGlover

- add API calls to `getViewData` in statement handler in order to display the PSC name
- this only displays a PSC name for Co # `00006400` and the  PSC Id hardcoded in PSC Verification resource - to be replaced when PSC list patches the selected PSC
- `formatDateBorn` put in `utils/index.ts` for use on PSC list screen, but maybe actual util file could be better named
- `executePost` handler added which is where the PSC Verification patch would be done with the statements - to follow in story IDVA£-1500
- tests added

IDVA3-575

<img width="1144" alt="Screenshot 2024-05-10 at 1 42 08 PM" src="https://github.com/companieshouse/psc-verification-web/assets/2736331/41bc0563-6f40-47b7-a3b9-67be637eb536">

2024-05-11 11:42 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-15 09:59 UTC, AlisonGriffiths requested changes

2024-05-15 09:59 UTC, AlisonGriffiths commented on test/routers/handlers/individual-statement/individualStatement.int.ts
> +import { parse } from "node-html-parser";
This library node-html-parser is not currently used within Companies House.
Either we we can investigate getting this library approved or the test needs to be rewritten without it.

2024-05-16 09:53 UTC, clewis1 approved these changes
Looks good

2024-05-16 10:35 UTC, AlisonGriffiths approved these changes

2024-05-16 10:35 UTC, merged