Feature/add psc verification patch to store psc list selection
companieshouse/psc-verification-web pull request #98
Opened 2024-05-17 10:09 UTC by eedwards0

<u>Add functionality to populate the individual PSC list page</u>
- `individualPscList.njk` - radio buttons dynamically populated with PSC individual data
- `individualPscListRouter.ts` - get and post methods call out to the IndividualPscListHandler
- `individualPscListHandler.ts`- retrieves the company profile via the Company Profile Service to retrieve the company name; retrieves the company individual PSC list via the Company PSC Service. The company PSC list is then rendered for the view. This file has also been renamed from individualPscList.ts
- new tests added and updated for the above `ts` files

<u>Notes</u>
- Patch will be addressed in ticket IDVA3-1504
- Radio button selection across locales will be addressed in future ticket

2024-05-17 15:27 UTC, hepsimo requested changes
Changes look good, but missing unit test for individualPscListHander. See e.g. individualStatement.unit.ts. Also a few minor suggestions/fixes.

2024-05-17 15:27 UTC, hepsimo commented on test/services/pscService.unit.ts
> +import { COMPANY_NUMBER, PSC_ID, PSC_INDIVIDUAL } from "../mocks/Psc.mock";
File was renamed to "psc.mock.ts" by an earlier PR, so this gives me missing import error.

2024-05-20 07:37 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-20 12:00 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-20 12:03 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-20 16:06 UTC, merged